version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
      prefix: build
      include: scope
  groups:
    maven-dependencies:
      applies-to: version-updates
      patterns:
        - "*"
  open-pull-requests-limit: 10

- package-ecosystem: "github-actions"
  directory: "/" # Location of package manifests
  schedule:
    interval: "weekly"
  commit-message:
    prefix: ci
    include: scope
  groups:
    github-actions-dependencies:
      applies-to: version-updates
      patterns:
        - "*"
